export const BOARD_ACTION_TYPES = {
  SET_BOARDS_DATA_ARRAY: "SET_BOARDS_DATA_ARRAY/boards",
  UPDATE_BOARDS_ARRAY: "UPDATE_BOARDS_ARRAY/boards",
  SET_BOARDS_OBJECT: "SET_BOARDS_OBJECT/boards",
  CREATE_NEW_BOARD: "CREATE_NEW_BOARD/board",
};
